- name: Install Apache and PHP for Ubuntu Server
  tags: apache,apache2,ubuntu 
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Apache and PHP for RedHat Server
  tags: apache,httpd,RedHat
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "RedHat"

- name: Start httpd (RedHat)
  tags: apache,RedHat,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: copy html file for site
  tags: apache,apache2,html
  copy: 
    src: /home/ubuntu/Ansible/roles/web_servers/files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644 
