---

- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Apache (Ubuntu)
      apt:
        name: 
          - apache2
          - libapache2-mod-php  
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache (RHEL/CentOS/Amazon)
      yum:
        name: 
          - httpd
          - php  
        state: latest
        update_cache: yes
      when: ansible_distribution in ["RedHat", "CentOS", "Amazon"]

