- name: Install unzip
  package:
    name: unzip
    
- name: Install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.12.1/terraform_1.12.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

